/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dlv } from "./dlv.js";

import * as z from "zod";

export interface Env {
  CRIBLMGMTPLANE_CLIENT_ID?: string | undefined;
  CRIBLMGMTPLANE_CLIENT_SECRET?: string | undefined;
  CRIBLMGMTPLANE_TOKEN_URL: string;
  CRIBLMGMTPLANE_AUDIENCE?: string | undefined;
  CRIBLMGMTPLANE_BEARER_AUTH?: string | undefined;

  CRIBLMGMTPLANE_DEBUG?: boolean | undefined;
}

export const envSchema: z.ZodType<Env, z.ZodTypeDef, unknown> = z.object({
  CRIBLMGMTPLANE_CLIENT_ID: z.string().optional(),
  CRIBLMGMTPLANE_CLIENT_SECRET: z.string().optional(),
  CRIBLMGMTPLANE_TOKEN_URL: z.string().default(
    "https://login.cribl.cloud/oauth/token",
  ),
  CRIBLMGMTPLANE_AUDIENCE: z.string().optional(),
  CRIBLMGMTPLANE_BEARER_AUTH: z.string().optional(),

  CRIBLMGMTPLANE_DEBUG: z.coerce.boolean().optional(),
});

let envMemo: Env | undefined = undefined;
/**
 * Reads and validates environment variables.
 */
export function env(): Env {
  if (envMemo) {
    return envMemo;
  }

  envMemo = envSchema.parse(
    dlv(globalThis, "process.env") ?? dlv(globalThis, "Deno.env") ?? {},
  );
  return envMemo;
}

/**
 * Clears the cached env object. Useful for testing with a fresh environment.
 */
export function resetEnv() {
  envMemo = undefined;
}
