/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as types from "../../types/primitives.js";
import { CriblMgmtPlaneError } from "./criblmgmtplaneerror.js";

export type DefaultErrorDTOData = {
  /**
   * HTTP status code.
   */
  statusCode: number;
  /**
   * Human-readable error message.
   */
  message: string;
};

export class DefaultErrorDTO extends CriblMgmtPlaneError {
  /** The original data that was passed to this error instance. */
  data$: DefaultErrorDTOData;

  constructor(
    err: DefaultErrorDTOData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "DefaultErrorDTO";
  }
}

/** @internal */
export const DefaultErrorDTO$inboundSchema: z.ZodType<
  DefaultErrorDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  statusCode: types.number(),
  message: types.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DefaultErrorDTO(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
