/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dummyServiceStatus } from "../../funcs/dummyServiceStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$dummyServiceStatus: ToolDefinition = {
  name: "dummy-service-status",
  description: `Service status`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await dummyServiceStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
