/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { test } from "vitest";
import { CriblMgmtPlane } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Criblmgmtplane Dummy Service Status", async () => {
  const testHttpClient = createTestHTTPClient("dummyServiceStatus");

  const criblMgmtPlane = new CriblMgmtPlane({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["CRIBLMGMTPLANE_BEARER_AUTH"] ?? "value",
  });

  await criblMgmtPlane.dummyServiceStatus();
});
