/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiCredentialsList } from "../funcs/apiCredentialsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApiCredentials extends ClientSDK {
  /**
   * List API credentials for an Organization
   *
   * @remarks
   * Retrieve all API credentials for the specified Organization.
   */
  async list(
    request: operations.V1ApiCredentialsListApiCredentialsRequest,
    options?: RequestOptions,
  ): Promise<operations.V1ApiCredentialsListApiCredentialsResponse> {
    return unwrapAsync(apiCredentialsList(
      this,
      request,
      options,
    ));
  }
}
