/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiCredentialsCreate } from "../funcs/apiCredentialsCreate.js";
import { apiCredentialsDelete } from "../funcs/apiCredentialsDelete.js";
import { apiCredentialsGet } from "../funcs/apiCredentialsGet.js";
import { apiCredentialsList } from "../funcs/apiCredentialsList.js";
import { apiCredentialsUpdate } from "../funcs/apiCredentialsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApiCredentials extends ClientSDK {
  /**
   * List API Credentials for an Organization
   *
   * @remarks
   * Get a list of all API Credentials for the specified Organization.
   */
  async list(
    request: operations.V1ApiCredentialsListApiCredentialsRequest,
    options?: RequestOptions,
  ): Promise<operations.V1ApiCredentialsListApiCredentialsResponse> {
    return unwrapAsync(apiCredentialsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an API Credential
   *
   * @remarks
   * Create a new API Credential for the specified Organization.
   */
  async create(
    request: operations.V1ApiCredentialsCreateApiCredentialRequest,
    options?: RequestOptions,
  ): Promise<operations.V1ApiCredentialsCreateApiCredentialResponse> {
    return unwrapAsync(apiCredentialsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an API Credential
   *
   * @remarks
   * Update the specified API Credential.
   */
  async update(
    request: operations.V1ApiCredentialsUpdateApiCredentialRequest,
    options?: RequestOptions,
  ): Promise<models.DefaultErrorDTO | undefined> {
    return unwrapAsync(apiCredentialsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an API Credential
   *
   * @remarks
   * Delete the specified API Credential.
   */
  async delete(
    request: operations.V1ApiCredentialsDeleteApiCredentialRequest,
    options?: RequestOptions,
  ): Promise<models.DefaultErrorDTO | undefined> {
    return unwrapAsync(apiCredentialsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an API Credential
   *
   * @remarks
   * Get the specified API Credential.
   */
  async get(
    request: operations.V1ApiCredentialsGetApiCredentialRequest,
    options?: RequestOptions,
  ): Promise<operations.V1ApiCredentialsGetApiCredentialResponse> {
    return unwrapAsync(apiCredentialsGet(
      this,
      request,
      options,
    ));
  }
}
