/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingGetContractsUtilization } from "../funcs/billingGetContractsUtilization.js";
import { billingGetCreditsGrants } from "../funcs/billingGetCreditsGrants.js";
import { billingGetCreditsStats } from "../funcs/billingGetCreditsStats.js";
import { billingGetCreditsTimeseries } from "../funcs/billingGetCreditsTimeseries.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Billing extends ClientSDK {
  /**
   * [In development] Get contract credit utilization
   *
   * @remarks
   * **This endpoint is in development with restricted availability**. We do not recommend using this endpoint in production. Functionality might change without notice. Contact [Cribl Support](https://cribl.io/support/) to request access.
   *
   * Get cumulative credit utilization data grouped by contract period for the specified Organization.
   */
  async getContractsUtilization(
    request: operations.V1BillingGetContractsUtilizationRequest,
    options?: RequestOptions,
  ): Promise<operations.V1BillingGetContractsUtilizationResponse> {
    return unwrapAsync(billingGetContractsUtilization(
      this,
      request,
      options,
    ));
  }

  /**
   * [In development] Get credits timeseries
   *
   * @remarks
   * **This endpoint is in development with restricted availability**. We do not recommend using this endpoint in production. Functionality might change without notice. Contact [Cribl Support](https://cribl.io/support/) to request access.
   *
   * Get credit consumption timeseries data for the specified Organization, broken down by dimensions such as product and usage type.
   */
  async getCreditsTimeseries(
    request: operations.V1BillingGetCreditsTimeseriesRequest,
    options?: RequestOptions,
  ): Promise<operations.V1BillingGetCreditsTimeseriesResponse> {
    return unwrapAsync(billingGetCreditsTimeseries(
      this,
      request,
      options,
    ));
  }

  /**
   * [In development] Get credit balance and consumption
   *
   * @remarks
   * **This endpoint is in development with restricted availability**. We do not recommend using this endpoint in production. Functionality might change without notice. Contact [Cribl Support](https://cribl.io/support/) to request access.
   *
   * Get credit balance totals, consumption totals, and contract date ranges for the specified Organization.
   */
  async getCreditsStats(
    request: operations.V1BillingGetCreditsStatsRequest,
    options?: RequestOptions,
  ): Promise<operations.V1BillingGetCreditsStatsResponse> {
    return unwrapAsync(billingGetCreditsStats(
      this,
      request,
      options,
    ));
  }

  /**
   * [In development] Get credit grants
   *
   * @remarks
   * **This endpoint is in development with restricted availability**. We do not recommend using this endpoint in production. Functionality might change without notice. Contact [Cribl Support](https://cribl.io/support/) to request access.
   *
   * Get credit grants (purchases, rollovers, and refunds) for the specified Organization.
   */
  async getCreditsGrants(
    request: operations.V1BillingGetCreditsGrantsRequest,
    options?: RequestOptions,
  ): Promise<operations.V1BillingGetCreditsGrantsResponse> {
    return unwrapAsync(billingGetCreditsGrants(
      this,
      request,
      options,
    ));
  }
}
