/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGet } from "../funcs/healthGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Get the health status of the application
   */
  async get(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(healthGet(
      this,
      options,
    ));
  }
}
