/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { ApiCredentials } from "./apicredentials.js";
import { Health } from "./health.js";
import { Workspaces } from "./workspaces.js";

export class CriblMgmtPlane extends ClientSDK {
  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _apiCredentials?: ApiCredentials;
  get apiCredentials(): ApiCredentials {
    return (this._apiCredentials ??= new ApiCredentials(this._options));
  }

  private _workspaces?: Workspaces;
  get workspaces(): Workspaces {
    return (this._workspaces ??= new Workspaces(this._options));
  }
}
