/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dummyServiceStatus } from "../funcs/dummyServiceStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class CriblMgmtPlane extends ClientSDK {
  /**
   * Service status
   */
  async dummyServiceStatus(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(dummyServiceStatus(
      this,
      options,
    ));
  }
}
