/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesV1WorkspacesCreateWorkspace } from "../funcs/workspacesV1WorkspacesCreateWorkspace.js";
import { workspacesV1WorkspacesDeleteWorkspace } from "../funcs/workspacesV1WorkspacesDeleteWorkspace.js";
import { workspacesV1WorkspacesGetWorkspace } from "../funcs/workspacesV1WorkspacesGetWorkspace.js";
import { workspacesV1WorkspacesListWorkspaces } from "../funcs/workspacesV1WorkspacesListWorkspaces.js";
import { workspacesV1WorkspacesUpdateWorkspace } from "../funcs/workspacesV1WorkspacesUpdateWorkspace.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Workspaces extends ClientSDK {
  /**
   * Create a new workspace
   */
  async v1WorkspacesCreateWorkspace(
    security: operations.V1WorkspacesCreateWorkspaceSecurity,
    request: operations.V1WorkspacesCreateWorkspaceRequest,
    options?: RequestOptions,
  ): Promise<models.WorkspaceSchema> {
    return unwrapAsync(workspacesV1WorkspacesCreateWorkspace(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List all workspaces for an organization
   */
  async v1WorkspacesListWorkspaces(
    security: operations.V1WorkspacesListWorkspacesSecurity,
    request: operations.V1WorkspacesListWorkspacesRequest,
    options?: RequestOptions,
  ): Promise<models.WorkspacesListResponseDTO> {
    return unwrapAsync(workspacesV1WorkspacesListWorkspaces(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an existing workspace
   */
  async v1WorkspacesUpdateWorkspace(
    security: operations.V1WorkspacesUpdateWorkspaceSecurity,
    request: operations.V1WorkspacesUpdateWorkspaceRequest,
    options?: RequestOptions,
  ): Promise<models.WorkspaceSchema> {
    return unwrapAsync(workspacesV1WorkspacesUpdateWorkspace(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a workspace
   */
  async v1WorkspacesDeleteWorkspace(
    security: operations.V1WorkspacesDeleteWorkspaceSecurity,
    request: operations.V1WorkspacesDeleteWorkspaceRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(workspacesV1WorkspacesDeleteWorkspace(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a specific workspace by ID
   */
  async v1WorkspacesGetWorkspace(
    security: operations.V1WorkspacesGetWorkspaceSecurity,
    request: operations.V1WorkspacesGetWorkspaceRequest,
    options?: RequestOptions,
  ): Promise<models.WorkspaceSchema> {
    return unwrapAsync(workspacesV1WorkspacesGetWorkspace(
      this,
      security,
      request,
      options,
    ));
  }
}
