/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the cribl-mgmt-plane SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx dummyServiceStatus.ts
 */

import { CriblMgmtPlane } from "cribl-mgmt-plane";

const criblMgmtPlane = new CriblMgmtPlane({
  serverURL: "https://api.example.com",
  bearerAuth: process.env["CRIBLMGMTPLANE_BEARER_AUTH"] ?? "",
});

async function main() {
  await criblMgmtPlane.dummyServiceStatus();
}

main().catch(console.error);
