/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the cribl-mgmt-plane SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthGetHealthStatus.ts
 */

import { CriblMgmtPlane } from "cribl-mgmt-plane";

const criblMgmtPlane = new CriblMgmtPlane({
  security: {
    clientID: process.env["CRIBLMGMTPLANE_CLIENT_ID"] ?? "",
    clientSecret: process.env["CRIBLMGMTPLANE_CLIENT_SECRET"] ?? "",
  },
});

async function main() {
  await criblMgmtPlane.getHealthStatus();
}

main().catch(console.error);
