workflowVersion: 1.0.0
speakeasyVersion: 1.606.0
sources:
    Cribl Cloud Management API:
        inputs:
            - location: https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/mgmt-plane.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api
targets:
    cribl-mgmt-plane:
        target: typescript
        source: Cribl Cloud Management API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: false
