/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Health status
 */
export type GetHealthStatusResponseBody = {
  status?: string | undefined;
};

export type GetHealthStatusResponse =
  | models.DefaultErrorDTO
  | GetHealthStatusResponseBody;

/** @internal */
export const GetHealthStatusResponseBody$inboundSchema: z.ZodType<
  GetHealthStatusResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string().optional(),
});

export function getHealthStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const GetHealthStatusResponse$inboundSchema: z.ZodType<
  GetHealthStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.DefaultErrorDTO$inboundSchema,
  z.lazy(() => GetHealthStatusResponseBody$inboundSchema),
]);

export function getHealthStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthStatusResponse' from JSON`,
  );
}
