/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1ApiCredentialsDeleteApiCredentialRequest = {
  /**
   * The <code>id</code> of the Organization whose API Credential you want to delete.
   */
  organizationId: string;
  /**
   * The <code>clientId</code> of the API Credential to delete.
   */
  apiCredentialId: string;
};

/** @internal */
export type V1ApiCredentialsDeleteApiCredentialRequest$Outbound = {
  organizationId: string;
  apiCredentialId: string;
};

/** @internal */
export const V1ApiCredentialsDeleteApiCredentialRequest$outboundSchema:
  z.ZodType<
    V1ApiCredentialsDeleteApiCredentialRequest$Outbound,
    z.ZodTypeDef,
    V1ApiCredentialsDeleteApiCredentialRequest
  > = z.object({
    organizationId: z.string(),
    apiCredentialId: z.string(),
  });

export function v1ApiCredentialsDeleteApiCredentialRequestToJSON(
  v1ApiCredentialsDeleteApiCredentialRequest:
    V1ApiCredentialsDeleteApiCredentialRequest,
): string {
  return JSON.stringify(
    V1ApiCredentialsDeleteApiCredentialRequest$outboundSchema.parse(
      v1ApiCredentialsDeleteApiCredentialRequest,
    ),
  );
}
