/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type V1ApiCredentialsUpdateApiCredentialRequest = {
  /**
   * The <code>id</code> of the Organization whose API Credential you want to update.
   */
  organizationId: string;
  /**
   * The <code>clientId</code> of the API Credential to update.
   */
  apiCredentialId: string;
  apiCredentialUpdateRequestDTO: models.ApiCredentialUpdateRequestDTO;
};

/** @internal */
export type V1ApiCredentialsUpdateApiCredentialRequest$Outbound = {
  organizationId: string;
  apiCredentialId: string;
  ApiCredentialUpdateRequestDTO: models.ApiCredentialUpdateRequestDTO$Outbound;
};

/** @internal */
export const V1ApiCredentialsUpdateApiCredentialRequest$outboundSchema:
  z.ZodType<
    V1ApiCredentialsUpdateApiCredentialRequest$Outbound,
    z.ZodTypeDef,
    V1ApiCredentialsUpdateApiCredentialRequest
  > = z.object({
    organizationId: z.string(),
    apiCredentialId: z.string(),
    apiCredentialUpdateRequestDTO:
      models.ApiCredentialUpdateRequestDTO$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      apiCredentialUpdateRequestDTO: "ApiCredentialUpdateRequestDTO",
    });
  });

export function v1ApiCredentialsUpdateApiCredentialRequestToJSON(
  v1ApiCredentialsUpdateApiCredentialRequest:
    V1ApiCredentialsUpdateApiCredentialRequest,
): string {
  return JSON.stringify(
    V1ApiCredentialsUpdateApiCredentialRequest$outboundSchema.parse(
      v1ApiCredentialsUpdateApiCredentialRequest,
    ),
  );
}
