/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1ApiCredentialsGetApiCredentialRequest = {
  /**
   * The <code>id</code> of the Organization whose API Credential you want to retrieve.
   */
  organizationId: string;
  /**
   * The <code>clientId</code> of the API Credential to retrieve.
   */
  apiCredentialId: string;
};

export type V1ApiCredentialsGetApiCredentialResponse =
  | models.ApiCredentialResponseSchema
  | models.DefaultErrorDTO;

/** @internal */
export type V1ApiCredentialsGetApiCredentialRequest$Outbound = {
  organizationId: string;
  apiCredentialId: string;
};

/** @internal */
export const V1ApiCredentialsGetApiCredentialRequest$outboundSchema: z.ZodType<
  V1ApiCredentialsGetApiCredentialRequest$Outbound,
  z.ZodTypeDef,
  V1ApiCredentialsGetApiCredentialRequest
> = z.object({
  organizationId: z.string(),
  apiCredentialId: z.string(),
});

export function v1ApiCredentialsGetApiCredentialRequestToJSON(
  v1ApiCredentialsGetApiCredentialRequest:
    V1ApiCredentialsGetApiCredentialRequest,
): string {
  return JSON.stringify(
    V1ApiCredentialsGetApiCredentialRequest$outboundSchema.parse(
      v1ApiCredentialsGetApiCredentialRequest,
    ),
  );
}

/** @internal */
export const V1ApiCredentialsGetApiCredentialResponse$inboundSchema: z.ZodType<
  V1ApiCredentialsGetApiCredentialResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.ApiCredentialResponseSchema$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1ApiCredentialsGetApiCredentialResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V1ApiCredentialsGetApiCredentialResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1ApiCredentialsGetApiCredentialResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1ApiCredentialsGetApiCredentialResponse' from JSON`,
  );
}
