/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1ApiCredentialsListApiCredentialsRequest = {
  /**
   * The <code>id</code> of the Organization whose API Credentials you want to list.
   */
  organizationId: string;
};

export type V1ApiCredentialsListApiCredentialsResponse =
  | models.ApiCredentialsListResponseDTO
  | models.DefaultErrorDTO;

/** @internal */
export type V1ApiCredentialsListApiCredentialsRequest$Outbound = {
  organizationId: string;
};

/** @internal */
export const V1ApiCredentialsListApiCredentialsRequest$outboundSchema:
  z.ZodType<
    V1ApiCredentialsListApiCredentialsRequest$Outbound,
    z.ZodTypeDef,
    V1ApiCredentialsListApiCredentialsRequest
  > = z.object({
    organizationId: z.string(),
  });

export function v1ApiCredentialsListApiCredentialsRequestToJSON(
  v1ApiCredentialsListApiCredentialsRequest:
    V1ApiCredentialsListApiCredentialsRequest,
): string {
  return JSON.stringify(
    V1ApiCredentialsListApiCredentialsRequest$outboundSchema.parse(
      v1ApiCredentialsListApiCredentialsRequest,
    ),
  );
}

/** @internal */
export const V1ApiCredentialsListApiCredentialsResponse$inboundSchema:
  z.ZodType<V1ApiCredentialsListApiCredentialsResponse, z.ZodTypeDef, unknown> =
    smartUnion([
      models.ApiCredentialsListResponseDTO$inboundSchema,
      models.DefaultErrorDTO$inboundSchema,
    ]);

export function v1ApiCredentialsListApiCredentialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V1ApiCredentialsListApiCredentialsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1ApiCredentialsListApiCredentialsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1ApiCredentialsListApiCredentialsResponse' from JSON`,
  );
}
