/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1ApiCredentialsCreateApiCredentialRequest = {
  /**
   * The <code>id</code> of the Organization where you want to create the API Credential.
   */
  organizationId: string;
  apiCredentialCreateRequestDTO: models.ApiCredentialCreateRequestDTO;
};

export type V1ApiCredentialsCreateApiCredentialResponse =
  | models.ApiCredentialResponseSchema
  | models.DefaultErrorDTO;

/** @internal */
export type V1ApiCredentialsCreateApiCredentialRequest$Outbound = {
  organizationId: string;
  ApiCredentialCreateRequestDTO: models.ApiCredentialCreateRequestDTO$Outbound;
};

/** @internal */
export const V1ApiCredentialsCreateApiCredentialRequest$outboundSchema:
  z.ZodType<
    V1ApiCredentialsCreateApiCredentialRequest$Outbound,
    z.ZodTypeDef,
    V1ApiCredentialsCreateApiCredentialRequest
  > = z.object({
    organizationId: z.string(),
    apiCredentialCreateRequestDTO:
      models.ApiCredentialCreateRequestDTO$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      apiCredentialCreateRequestDTO: "ApiCredentialCreateRequestDTO",
    });
  });

export function v1ApiCredentialsCreateApiCredentialRequestToJSON(
  v1ApiCredentialsCreateApiCredentialRequest:
    V1ApiCredentialsCreateApiCredentialRequest,
): string {
  return JSON.stringify(
    V1ApiCredentialsCreateApiCredentialRequest$outboundSchema.parse(
      v1ApiCredentialsCreateApiCredentialRequest,
    ),
  );
}

/** @internal */
export const V1ApiCredentialsCreateApiCredentialResponse$inboundSchema:
  z.ZodType<
    V1ApiCredentialsCreateApiCredentialResponse,
    z.ZodTypeDef,
    unknown
  > = smartUnion([
    models.ApiCredentialResponseSchema$inboundSchema,
    models.DefaultErrorDTO$inboundSchema,
  ]);

export function v1ApiCredentialsCreateApiCredentialResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V1ApiCredentialsCreateApiCredentialResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1ApiCredentialsCreateApiCredentialResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1ApiCredentialsCreateApiCredentialResponse' from JSON`,
  );
}
