/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1BillingGetContractsUtilizationRequest = {
  /**
   * The <code>id</code> of the Organization.
   */
  organizationId: string;
  /**
   * Inclusive start of the query date range in ISO 8601 format.
   */
  startingOn: Date;
  /**
   * Exclusive end of the query date range in ISO 8601 format.
   */
  endingBefore: Date;
  /**
   * Aggregation granularity for credit utilization data.
   */
  window: models.BillingWindow;
};

export type V1BillingGetContractsUtilizationResponse =
  | models.DefaultErrorDTO
  | models.ContractsUtilizationResponseDTO;

/** @internal */
export type V1BillingGetContractsUtilizationRequest$Outbound = {
  organizationId: string;
  startingOn: string;
  endingBefore: string;
  window: string;
};

/** @internal */
export const V1BillingGetContractsUtilizationRequest$outboundSchema: z.ZodType<
  V1BillingGetContractsUtilizationRequest$Outbound,
  z.ZodTypeDef,
  V1BillingGetContractsUtilizationRequest
> = z.object({
  organizationId: z.string(),
  startingOn: z.date().transform(v => v.toISOString()),
  endingBefore: z.date().transform(v => v.toISOString()),
  window: models.BillingWindow$outboundSchema,
});

export function v1BillingGetContractsUtilizationRequestToJSON(
  v1BillingGetContractsUtilizationRequest:
    V1BillingGetContractsUtilizationRequest,
): string {
  return JSON.stringify(
    V1BillingGetContractsUtilizationRequest$outboundSchema.parse(
      v1BillingGetContractsUtilizationRequest,
    ),
  );
}

/** @internal */
export const V1BillingGetContractsUtilizationResponse$inboundSchema: z.ZodType<
  V1BillingGetContractsUtilizationResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.DefaultErrorDTO$inboundSchema,
  models.ContractsUtilizationResponseDTO$inboundSchema,
]);

export function v1BillingGetContractsUtilizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V1BillingGetContractsUtilizationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1BillingGetContractsUtilizationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1BillingGetContractsUtilizationResponse' from JSON`,
  );
}
