/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1BillingGetCreditsGrantsRequest = {
  /**
   * The <code>id</code> of the Organization.
   */
  organizationId: string;
  /**
   * Inclusive start of the query date range in ISO 8601 format.
   */
  startingOn: Date;
  /**
   * Exclusive end of the query date range in ISO 8601 format.
   */
  endingBefore: Date;
  /**
   * Aggregation granularity for credit grant data.
   */
  window: models.BillingWindow;
};

export type V1BillingGetCreditsGrantsResponse =
  | models.CreditGrantsResponseDTO
  | models.DefaultErrorDTO;

/** @internal */
export type V1BillingGetCreditsGrantsRequest$Outbound = {
  organizationId: string;
  startingOn: string;
  endingBefore: string;
  window: string;
};

/** @internal */
export const V1BillingGetCreditsGrantsRequest$outboundSchema: z.ZodType<
  V1BillingGetCreditsGrantsRequest$Outbound,
  z.ZodTypeDef,
  V1BillingGetCreditsGrantsRequest
> = z.object({
  organizationId: z.string(),
  startingOn: z.date().transform(v => v.toISOString()),
  endingBefore: z.date().transform(v => v.toISOString()),
  window: models.BillingWindow$outboundSchema,
});

export function v1BillingGetCreditsGrantsRequestToJSON(
  v1BillingGetCreditsGrantsRequest: V1BillingGetCreditsGrantsRequest,
): string {
  return JSON.stringify(
    V1BillingGetCreditsGrantsRequest$outboundSchema.parse(
      v1BillingGetCreditsGrantsRequest,
    ),
  );
}

/** @internal */
export const V1BillingGetCreditsGrantsResponse$inboundSchema: z.ZodType<
  V1BillingGetCreditsGrantsResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.CreditGrantsResponseDTO$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1BillingGetCreditsGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1BillingGetCreditsGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1BillingGetCreditsGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BillingGetCreditsGrantsResponse' from JSON`,
  );
}
