/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1BillingGetCreditsStatsRequest = {
  /**
   * The <code>id</code> of the Organization.
   */
  organizationId: string;
  /**
   * Inclusive start of the query date range in ISO 8601 format.
   */
  startingOn: Date;
  /**
   * Exclusive end of the query date range in ISO 8601 format.
   */
  endingBefore: Date;
  /**
   * Aggregation granularity for credit balance and consumption.
   */
  window: models.BillingWindow;
};

export type V1BillingGetCreditsStatsResponse =
  | models.CreditsStatsResponseDTO
  | models.DefaultErrorDTO;

/** @internal */
export type V1BillingGetCreditsStatsRequest$Outbound = {
  organizationId: string;
  startingOn: string;
  endingBefore: string;
  window: string;
};

/** @internal */
export const V1BillingGetCreditsStatsRequest$outboundSchema: z.ZodType<
  V1BillingGetCreditsStatsRequest$Outbound,
  z.ZodTypeDef,
  V1BillingGetCreditsStatsRequest
> = z.object({
  organizationId: z.string(),
  startingOn: z.date().transform(v => v.toISOString()),
  endingBefore: z.date().transform(v => v.toISOString()),
  window: models.BillingWindow$outboundSchema,
});

export function v1BillingGetCreditsStatsRequestToJSON(
  v1BillingGetCreditsStatsRequest: V1BillingGetCreditsStatsRequest,
): string {
  return JSON.stringify(
    V1BillingGetCreditsStatsRequest$outboundSchema.parse(
      v1BillingGetCreditsStatsRequest,
    ),
  );
}

/** @internal */
export const V1BillingGetCreditsStatsResponse$inboundSchema: z.ZodType<
  V1BillingGetCreditsStatsResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.CreditsStatsResponseDTO$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1BillingGetCreditsStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1BillingGetCreditsStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1BillingGetCreditsStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BillingGetCreditsStatsResponse' from JSON`,
  );
}
