/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1BillingGetCreditsTimeseriesRequest = {
  /**
   * The <code>id</code> of the Organization.
   */
  organizationId: string;
  /**
   * Inclusive start of the query date range in ISO 8601 format.
   */
  startingOn: Date;
  /**
   * Exclusive end of the query date range in ISO 8601 format.
   */
  endingBefore: Date;
  /**
   * Aggregation granularity for timeseries data.
   */
  window: models.BillingWindow;
};

export type V1BillingGetCreditsTimeseriesResponse =
  | models.CreditsTimeseriesResponseDTO
  | models.DefaultErrorDTO;

/** @internal */
export type V1BillingGetCreditsTimeseriesRequest$Outbound = {
  organizationId: string;
  startingOn: string;
  endingBefore: string;
  window: string;
};

/** @internal */
export const V1BillingGetCreditsTimeseriesRequest$outboundSchema: z.ZodType<
  V1BillingGetCreditsTimeseriesRequest$Outbound,
  z.ZodTypeDef,
  V1BillingGetCreditsTimeseriesRequest
> = z.object({
  organizationId: z.string(),
  startingOn: z.date().transform(v => v.toISOString()),
  endingBefore: z.date().transform(v => v.toISOString()),
  window: models.BillingWindow$outboundSchema,
});

export function v1BillingGetCreditsTimeseriesRequestToJSON(
  v1BillingGetCreditsTimeseriesRequest: V1BillingGetCreditsTimeseriesRequest,
): string {
  return JSON.stringify(
    V1BillingGetCreditsTimeseriesRequest$outboundSchema.parse(
      v1BillingGetCreditsTimeseriesRequest,
    ),
  );
}

/** @internal */
export const V1BillingGetCreditsTimeseriesResponse$inboundSchema: z.ZodType<
  V1BillingGetCreditsTimeseriesResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.CreditsTimeseriesResponseDTO$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1BillingGetCreditsTimeseriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1BillingGetCreditsTimeseriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1BillingGetCreditsTimeseriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BillingGetCreditsTimeseriesResponse' from JSON`,
  );
}
