/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1WorkspacesListWorkspacesRequest = {
  /**
   * The <code>id</code> of the Organization that contains the Workspaces.
   */
  organizationId: string;
};

export type V1WorkspacesListWorkspacesResponse =
  | models.WorkspacesListResponseDTO
  | models.DefaultErrorDTO;

/** @internal */
export type V1WorkspacesListWorkspacesRequest$Outbound = {
  organizationId: string;
};

/** @internal */
export const V1WorkspacesListWorkspacesRequest$outboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesListWorkspacesRequest
> = z.object({
  organizationId: z.string(),
});

export function v1WorkspacesListWorkspacesRequestToJSON(
  v1WorkspacesListWorkspacesRequest: V1WorkspacesListWorkspacesRequest,
): string {
  return JSON.stringify(
    V1WorkspacesListWorkspacesRequest$outboundSchema.parse(
      v1WorkspacesListWorkspacesRequest,
    ),
  );
}

/** @internal */
export const V1WorkspacesListWorkspacesResponse$inboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.WorkspacesListResponseDTO$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1WorkspacesListWorkspacesResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesListWorkspacesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1WorkspacesListWorkspacesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesListWorkspacesResponse' from JSON`,
  );
}
