/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1WorkspacesGetWorkspaceRequest = {
  /**
   * The <code>id</code> of the Organization that contains the Workspace.
   */
  organizationId: string;
  /**
   * The <code>id</code> of the Workspace to get.
   */
  workspaceId: string;
};

export type V1WorkspacesGetWorkspaceResponse =
  | models.WorkspaceSchema
  | models.DefaultErrorDTO;

/** @internal */
export type V1WorkspacesGetWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
};

/** @internal */
export const V1WorkspacesGetWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesGetWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

export function v1WorkspacesGetWorkspaceRequestToJSON(
  v1WorkspacesGetWorkspaceRequest: V1WorkspacesGetWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesGetWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesGetWorkspaceRequest,
    ),
  );
}

/** @internal */
export const V1WorkspacesGetWorkspaceResponse$inboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  models.WorkspaceSchema$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

export function v1WorkspacesGetWorkspaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesGetWorkspaceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesGetWorkspaceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesGetWorkspaceResponse' from JSON`,
  );
}
