/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1WorkspacesGetWorkspaceRequest = {
  /**
   * The <code>id</code> of the Organization that contains the Workspace.
   */
  organizationId: string;
  /**
   * The <code>id</code> of the Workspace to get.
   */
  workspaceId: string;
};

export type V1WorkspacesGetWorkspaceResponse =
  | models.WorkspaceSchema
  | models.DefaultErrorDTO;

/** @internal */
export const V1WorkspacesGetWorkspaceRequest$inboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

/** @internal */
export type V1WorkspacesGetWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
};

/** @internal */
export const V1WorkspacesGetWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesGetWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesGetWorkspaceRequest$ {
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesGetWorkspaceRequest$inboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$outboundSchema` instead. */
  export const outboundSchema = V1WorkspacesGetWorkspaceRequest$outboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$Outbound` instead. */
  export type Outbound = V1WorkspacesGetWorkspaceRequest$Outbound;
}

export function v1WorkspacesGetWorkspaceRequestToJSON(
  v1WorkspacesGetWorkspaceRequest: V1WorkspacesGetWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesGetWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesGetWorkspaceRequest,
    ),
  );
}

export function v1WorkspacesGetWorkspaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesGetWorkspaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesGetWorkspaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesGetWorkspaceRequest' from JSON`,
  );
}

/** @internal */
export const V1WorkspacesGetWorkspaceResponse$inboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.WorkspaceSchema$inboundSchema,
  models.DefaultErrorDTO$inboundSchema,
]);

/** @internal */
export type V1WorkspacesGetWorkspaceResponse$Outbound =
  | models.WorkspaceSchema$Outbound
  | models.DefaultErrorDTO$Outbound;

/** @internal */
export const V1WorkspacesGetWorkspaceResponse$outboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceResponse$Outbound,
  z.ZodTypeDef,
  V1WorkspacesGetWorkspaceResponse
> = z.union([
  models.WorkspaceSchema$outboundSchema,
  models.DefaultErrorDTO$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesGetWorkspaceResponse$ {
  /** @deprecated use `V1WorkspacesGetWorkspaceResponse$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesGetWorkspaceResponse$inboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceResponse$outboundSchema` instead. */
  export const outboundSchema = V1WorkspacesGetWorkspaceResponse$outboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceResponse$Outbound` instead. */
  export type Outbound = V1WorkspacesGetWorkspaceResponse$Outbound;
}

export function v1WorkspacesGetWorkspaceResponseToJSON(
  v1WorkspacesGetWorkspaceResponse: V1WorkspacesGetWorkspaceResponse,
): string {
  return JSON.stringify(
    V1WorkspacesGetWorkspaceResponse$outboundSchema.parse(
      v1WorkspacesGetWorkspaceResponse,
    ),
  );
}

export function v1WorkspacesGetWorkspaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesGetWorkspaceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesGetWorkspaceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesGetWorkspaceResponse' from JSON`,
  );
}
