/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1WorkspacesListWorkspacesSecurity = {
  oauth2?: models.SchemeOauth2 | undefined;
  bearer?: string | undefined;
};

export type V1WorkspacesListWorkspacesRequest = {
  /**
   * Organization identifier
   */
  organizationId: string;
};

/** @internal */
export const V1WorkspacesListWorkspacesSecurity$inboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  oauth2: models.SchemeOauth2$inboundSchema.optional(),
  bearer: z.string().optional(),
});

/** @internal */
export type V1WorkspacesListWorkspacesSecurity$Outbound = {
  oauth2?: models.SchemeOauth2$Outbound | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const V1WorkspacesListWorkspacesSecurity$outboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesSecurity$Outbound,
  z.ZodTypeDef,
  V1WorkspacesListWorkspacesSecurity
> = z.object({
  oauth2: models.SchemeOauth2$outboundSchema.optional(),
  bearer: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesListWorkspacesSecurity$ {
  /** @deprecated use `V1WorkspacesListWorkspacesSecurity$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesListWorkspacesSecurity$inboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesSecurity$outboundSchema` instead. */
  export const outboundSchema =
    V1WorkspacesListWorkspacesSecurity$outboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesSecurity$Outbound` instead. */
  export type Outbound = V1WorkspacesListWorkspacesSecurity$Outbound;
}

export function v1WorkspacesListWorkspacesSecurityToJSON(
  v1WorkspacesListWorkspacesSecurity: V1WorkspacesListWorkspacesSecurity,
): string {
  return JSON.stringify(
    V1WorkspacesListWorkspacesSecurity$outboundSchema.parse(
      v1WorkspacesListWorkspacesSecurity,
    ),
  );
}

export function v1WorkspacesListWorkspacesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesListWorkspacesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1WorkspacesListWorkspacesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesListWorkspacesSecurity' from JSON`,
  );
}

/** @internal */
export const V1WorkspacesListWorkspacesRequest$inboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
});

/** @internal */
export type V1WorkspacesListWorkspacesRequest$Outbound = {
  organizationId: string;
};

/** @internal */
export const V1WorkspacesListWorkspacesRequest$outboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesListWorkspacesRequest
> = z.object({
  organizationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesListWorkspacesRequest$ {
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesListWorkspacesRequest$inboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1WorkspacesListWorkspacesRequest$outboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$Outbound` instead. */
  export type Outbound = V1WorkspacesListWorkspacesRequest$Outbound;
}

export function v1WorkspacesListWorkspacesRequestToJSON(
  v1WorkspacesListWorkspacesRequest: V1WorkspacesListWorkspacesRequest,
): string {
  return JSON.stringify(
    V1WorkspacesListWorkspacesRequest$outboundSchema.parse(
      v1WorkspacesListWorkspacesRequest,
    ),
  );
}

export function v1WorkspacesListWorkspacesRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesListWorkspacesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesListWorkspacesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesListWorkspacesRequest' from JSON`,
  );
}
