/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1WorkspacesDeleteWorkspaceRequest = {
  /**
   * The <code>id</code> of the Organization that contains the Workspace.
   */
  organizationId: string;
  /**
   * The <code>id</code> of the Workspace to delete.
   */
  workspaceId: string;
};

/** @internal */
export type V1WorkspacesDeleteWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
};

/** @internal */
export const V1WorkspacesDeleteWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesDeleteWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesDeleteWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

export function v1WorkspacesDeleteWorkspaceRequestToJSON(
  v1WorkspacesDeleteWorkspaceRequest: V1WorkspacesDeleteWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesDeleteWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesDeleteWorkspaceRequest,
    ),
  );
}
