/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1WorkspacesListWorkspacesRequest = {
  /**
   * Organization identifier
   */
  organizationId: string;
};

/** @internal */
export const V1WorkspacesListWorkspacesRequest$inboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
});

/** @internal */
export type V1WorkspacesListWorkspacesRequest$Outbound = {
  organizationId: string;
};

/** @internal */
export const V1WorkspacesListWorkspacesRequest$outboundSchema: z.ZodType<
  V1WorkspacesListWorkspacesRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesListWorkspacesRequest
> = z.object({
  organizationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesListWorkspacesRequest$ {
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesListWorkspacesRequest$inboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1WorkspacesListWorkspacesRequest$outboundSchema;
  /** @deprecated use `V1WorkspacesListWorkspacesRequest$Outbound` instead. */
  export type Outbound = V1WorkspacesListWorkspacesRequest$Outbound;
}

export function v1WorkspacesListWorkspacesRequestToJSON(
  v1WorkspacesListWorkspacesRequest: V1WorkspacesListWorkspacesRequest,
): string {
  return JSON.stringify(
    V1WorkspacesListWorkspacesRequest$outboundSchema.parse(
      v1WorkspacesListWorkspacesRequest,
    ),
  );
}

export function v1WorkspacesListWorkspacesRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesListWorkspacesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesListWorkspacesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesListWorkspacesRequest' from JSON`,
  );
}
