/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type V1WorkspacesUpdateWorkspaceRequest = {
  /**
   * The <code>id</code> of the Organization that contains the Workspace.
   */
  organizationId: string;
  /**
   * The <code>id</code> of the Workspace to update.
   */
  workspaceId: string;
  workspacePatchRequestDTO: models.WorkspacePatchRequestDTO;
};

/** @internal */
export type V1WorkspacesUpdateWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
  WorkspacePatchRequestDTO: models.WorkspacePatchRequestDTO$Outbound;
};

/** @internal */
export const V1WorkspacesUpdateWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesUpdateWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesUpdateWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
  workspacePatchRequestDTO: models.WorkspacePatchRequestDTO$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    workspacePatchRequestDTO: "WorkspacePatchRequestDTO",
  });
});

export function v1WorkspacesUpdateWorkspaceRequestToJSON(
  v1WorkspacesUpdateWorkspaceRequest: V1WorkspacesUpdateWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesUpdateWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesUpdateWorkspaceRequest,
    ),
  );
}
