/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type V1WorkspacesUpdateWorkspaceSecurity = {
  oauth2?: models.SchemeOauth2 | undefined;
  bearer?: string | undefined;
};

export type V1WorkspacesUpdateWorkspaceRequest = {
  /**
   * Organization identifier
   */
  organizationId: string;
  /**
   * Workspace identifier
   */
  workspaceId: string;
  workspacePatchRequestDTO: models.WorkspacePatchRequestDTO;
};

/** @internal */
export const V1WorkspacesUpdateWorkspaceSecurity$inboundSchema: z.ZodType<
  V1WorkspacesUpdateWorkspaceSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  oauth2: models.SchemeOauth2$inboundSchema.optional(),
  bearer: z.string().optional(),
});

/** @internal */
export type V1WorkspacesUpdateWorkspaceSecurity$Outbound = {
  oauth2?: models.SchemeOauth2$Outbound | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const V1WorkspacesUpdateWorkspaceSecurity$outboundSchema: z.ZodType<
  V1WorkspacesUpdateWorkspaceSecurity$Outbound,
  z.ZodTypeDef,
  V1WorkspacesUpdateWorkspaceSecurity
> = z.object({
  oauth2: models.SchemeOauth2$outboundSchema.optional(),
  bearer: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesUpdateWorkspaceSecurity$ {
  /** @deprecated use `V1WorkspacesUpdateWorkspaceSecurity$inboundSchema` instead. */
  export const inboundSchema =
    V1WorkspacesUpdateWorkspaceSecurity$inboundSchema;
  /** @deprecated use `V1WorkspacesUpdateWorkspaceSecurity$outboundSchema` instead. */
  export const outboundSchema =
    V1WorkspacesUpdateWorkspaceSecurity$outboundSchema;
  /** @deprecated use `V1WorkspacesUpdateWorkspaceSecurity$Outbound` instead. */
  export type Outbound = V1WorkspacesUpdateWorkspaceSecurity$Outbound;
}

export function v1WorkspacesUpdateWorkspaceSecurityToJSON(
  v1WorkspacesUpdateWorkspaceSecurity: V1WorkspacesUpdateWorkspaceSecurity,
): string {
  return JSON.stringify(
    V1WorkspacesUpdateWorkspaceSecurity$outboundSchema.parse(
      v1WorkspacesUpdateWorkspaceSecurity,
    ),
  );
}

export function v1WorkspacesUpdateWorkspaceSecurityFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesUpdateWorkspaceSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1WorkspacesUpdateWorkspaceSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesUpdateWorkspaceSecurity' from JSON`,
  );
}

/** @internal */
export const V1WorkspacesUpdateWorkspaceRequest$inboundSchema: z.ZodType<
  V1WorkspacesUpdateWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
  WorkspacePatchRequestDTO: models.WorkspacePatchRequestDTO$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "WorkspacePatchRequestDTO": "workspacePatchRequestDTO",
  });
});

/** @internal */
export type V1WorkspacesUpdateWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
  WorkspacePatchRequestDTO: models.WorkspacePatchRequestDTO$Outbound;
};

/** @internal */
export const V1WorkspacesUpdateWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesUpdateWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesUpdateWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
  workspacePatchRequestDTO: models.WorkspacePatchRequestDTO$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    workspacePatchRequestDTO: "WorkspacePatchRequestDTO",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesUpdateWorkspaceRequest$ {
  /** @deprecated use `V1WorkspacesUpdateWorkspaceRequest$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesUpdateWorkspaceRequest$inboundSchema;
  /** @deprecated use `V1WorkspacesUpdateWorkspaceRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1WorkspacesUpdateWorkspaceRequest$outboundSchema;
  /** @deprecated use `V1WorkspacesUpdateWorkspaceRequest$Outbound` instead. */
  export type Outbound = V1WorkspacesUpdateWorkspaceRequest$Outbound;
}

export function v1WorkspacesUpdateWorkspaceRequestToJSON(
  v1WorkspacesUpdateWorkspaceRequest: V1WorkspacesUpdateWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesUpdateWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesUpdateWorkspaceRequest,
    ),
  );
}

export function v1WorkspacesUpdateWorkspaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesUpdateWorkspaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1WorkspacesUpdateWorkspaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesUpdateWorkspaceRequest' from JSON`,
  );
}
