/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1WorkspacesGetWorkspaceRequest = {
  /**
   * Organization identifier
   */
  organizationId: string;
  /**
   * Workspace identifier
   */
  workspaceId: string;
};

/** @internal */
export const V1WorkspacesGetWorkspaceRequest$inboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

/** @internal */
export type V1WorkspacesGetWorkspaceRequest$Outbound = {
  organizationId: string;
  workspaceId: string;
};

/** @internal */
export const V1WorkspacesGetWorkspaceRequest$outboundSchema: z.ZodType<
  V1WorkspacesGetWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  V1WorkspacesGetWorkspaceRequest
> = z.object({
  organizationId: z.string(),
  workspaceId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1WorkspacesGetWorkspaceRequest$ {
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$inboundSchema` instead. */
  export const inboundSchema = V1WorkspacesGetWorkspaceRequest$inboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$outboundSchema` instead. */
  export const outboundSchema = V1WorkspacesGetWorkspaceRequest$outboundSchema;
  /** @deprecated use `V1WorkspacesGetWorkspaceRequest$Outbound` instead. */
  export type Outbound = V1WorkspacesGetWorkspaceRequest$Outbound;
}

export function v1WorkspacesGetWorkspaceRequestToJSON(
  v1WorkspacesGetWorkspaceRequest: V1WorkspacesGetWorkspaceRequest,
): string {
  return JSON.stringify(
    V1WorkspacesGetWorkspaceRequest$outboundSchema.parse(
      v1WorkspacesGetWorkspaceRequest,
    ),
  );
}

export function v1WorkspacesGetWorkspaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1WorkspacesGetWorkspaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1WorkspacesGetWorkspaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1WorkspacesGetWorkspaceRequest' from JSON`,
  );
}
