/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$Outbound,
  ApiCredentialRolesSchema$outboundSchema,
} from "./apicredentialrolesschema.js";

export type ApiCredentialCreateRequestDTO = {
  /**
   * Human-readable name of the API Credential.
   */
  name: string;
  /**
   * Brief description of the purpose and usage for the API Credential.
   */
  description: string;
  /**
   * If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
   */
  enabled: boolean;
  /**
   * Role assignments for the API Credential.
   */
  roles: ApiCredentialRolesSchema;
  /**
   * CIDR range enforced as the IP allowlist for the API Credential.
   */
  ipAllowlist?: Array<string> | undefined;
};

/** @internal */
export type ApiCredentialCreateRequestDTO$Outbound = {
  name: string;
  description: string;
  enabled: boolean;
  roles: ApiCredentialRolesSchema$Outbound;
  ipAllowlist?: Array<string> | undefined;
};

/** @internal */
export const ApiCredentialCreateRequestDTO$outboundSchema: z.ZodType<
  ApiCredentialCreateRequestDTO$Outbound,
  z.ZodTypeDef,
  ApiCredentialCreateRequestDTO
> = z.object({
  name: z.string(),
  description: z.string(),
  enabled: z.boolean(),
  roles: ApiCredentialRolesSchema$outboundSchema,
  ipAllowlist: z.array(z.string()).optional(),
});

export function apiCredentialCreateRequestDTOToJSON(
  apiCredentialCreateRequestDTO: ApiCredentialCreateRequestDTO,
): string {
  return JSON.stringify(
    ApiCredentialCreateRequestDTO$outboundSchema.parse(
      apiCredentialCreateRequestDTO,
    ),
  );
}
