/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$inboundSchema,
} from "./apicredentialrolesschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiCredentialCreateResponseSchema = {
  /**
   * Human-readable name of the API Credential.
   */
  name: string;
  /**
   * Brief description of the purpose and usage for the API Credential.
   */
  description: string;
  /**
   * If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
   */
  enabled: boolean;
  /**
   * Unique ID of the Organization.
   */
  organizationId: string;
  /**
   * Client ID for the API Credential.
   */
  clientId: string;
  /**
   * Role assignments for the API Credential.
   */
  roles: ApiCredentialRolesSchema;
  /**
   * Member who created the API Credential.
   */
  createdBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was created.
   */
  createdDate: Date;
  /**
   * Member who last updated the API Credential.
   */
  lastUpdatedBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was last updated.
   */
  lastUpdatedDate: Date;
  /**
   * Client Secret for the API Credential. The Client Secret is sensitive information and should be kept private. Returned only in the <code>POST</code> response when the API Credential is created. Never returned in <code>GET</code> responses. If you need the Client Secret again, you must rotate credentials and retrieve the new Client Secret from the <code>POST</code> response.
   */
  clientSecret: string;
};

/** @internal */
export const ApiCredentialCreateResponseSchema$inboundSchema: z.ZodType<
  ApiCredentialCreateResponseSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.string(),
  description: types.string(),
  enabled: types.boolean(),
  organizationId: types.string(),
  clientId: types.string(),
  roles: ApiCredentialRolesSchema$inboundSchema,
  createdBy: types.string(),
  createdDate: types.date(),
  lastUpdatedBy: types.string(),
  lastUpdatedDate: types.date(),
  clientSecret: types.string(),
});

export function apiCredentialCreateResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialCreateResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialCreateResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialCreateResponseSchema' from JSON`,
  );
}
