/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$inboundSchema,
} from "./apicredentialrolesschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiCredentialListItemSchema = {
  /**
   * Human-readable name of the API Credential.
   */
  name: string;
  /**
   * Brief description of the purpose and usage for the API Credential.
   */
  description: string;
  /**
   * If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
   */
  enabled: boolean;
  /**
   * Unique ID of the Workspace.
   */
  workspaceId: string;
  /**
   * Unique ID of the Organization.
   */
  organizationId: string;
  /**
   * Client ID for the API Credential.
   */
  clientId: string;
  /**
   * Role assignments for the API Credential.
   */
  roles: ApiCredentialRolesSchema;
  /**
   * Member who created the API Credential.
   */
  createdBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was created.
   */
  createdDate: string;
  /**
   * Member who last updated the API Credential.
   */
  lastUpdatedBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was last updated.
   */
  lastUpdatedDate: string;
};

/** @internal */
export const ApiCredentialListItemSchema$inboundSchema: z.ZodType<
  ApiCredentialListItemSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.string(),
  description: types.string(),
  enabled: types.boolean(),
  workspaceId: types.string(),
  organizationId: types.string(),
  clientId: types.string(),
  roles: ApiCredentialRolesSchema$inboundSchema,
  createdBy: types.string(),
  createdDate: types.string(),
  lastUpdatedBy: types.string(),
  lastUpdatedDate: types.string(),
});

export function apiCredentialListItemSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialListItemSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialListItemSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialListItemSchema' from JSON`,
  );
}
