/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$inboundSchema,
} from "./apicredentialrolesschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiCredentialSchema = {
  /**
   * Human friendly name of the credential
   */
  name: string;
  /**
   * Description of how or where the credential is used
   */
  description: string;
  /**
   * Whether the credential is enabled
   */
  enabled: boolean;
  /**
   * Workspace identifier
   */
  workspaceId: string;
  /**
   * Organization identifier
   */
  organizationId: string;
  /**
   * Client identifier
   */
  clientId: string;
  /**
   * Client secret
   */
  clientSecret: string;
  /**
   * Role assignments for this credential
   */
  roles: ApiCredentialRolesSchema;
  /**
   * User who created the credential
   */
  createdBy: string;
  /**
   * ISO-8601 timestamp when the credential was created
   */
  createdDate: string;
  /**
   * User who last updated the credential
   */
  lastUpdatedBy: string;
  /**
   * ISO-8601 timestamp when the credential was last updated
   */
  lastUpdatedDate: string;
};

/** @internal */
export const ApiCredentialSchema$inboundSchema: z.ZodType<
  ApiCredentialSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.string(),
  description: types.string(),
  enabled: types.boolean(),
  workspaceId: types.string(),
  organizationId: types.string(),
  clientId: types.string(),
  clientSecret: types.string(),
  roles: ApiCredentialRolesSchema$inboundSchema,
  createdBy: types.string(),
  createdDate: types.string(),
  lastUpdatedBy: types.string(),
  lastUpdatedDate: types.string(),
});

export function apiCredentialSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialSchema' from JSON`,
  );
}
