/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$inboundSchema,
} from "./apicredentialrolesschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiCredentialResponseSchema = {
  /**
   * Human-readable name of the API Credential.
   */
  name: string;
  /**
   * Brief description of the purpose and usage for the API Credential.
   */
  description: string;
  /**
   * If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
   */
  enabled: boolean;
  /**
   * Unique ID of the Organization.
   */
  organizationId: string;
  /**
   * Client ID for the API Credential.
   */
  clientId: string;
  /**
   * Role assignments for the API Credential.
   */
  roles: ApiCredentialRolesSchema;
  /**
   * CIDR range enforced as the IP allowlist for the API Credential. An empty array means that the API Credential has no IP restrictions.
   */
  ipAllowlist: Array<string>;
  /**
   * Member who created the API Credential.
   */
  createdBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was created.
   */
  createdDate: Date;
  /**
   * Member who last updated the API Credential.
   */
  lastUpdatedBy: string;
  /**
   * ISO 8601 timestamp when the API Credential was last updated.
   */
  lastUpdatedDate: Date;
};

/** @internal */
export const ApiCredentialResponseSchema$inboundSchema: z.ZodType<
  ApiCredentialResponseSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.string(),
  description: types.string(),
  enabled: types.boolean(),
  organizationId: types.string(),
  clientId: types.string(),
  roles: ApiCredentialRolesSchema$inboundSchema,
  ipAllowlist: z.array(types.string()),
  createdBy: types.string(),
  createdDate: types.date(),
  lastUpdatedBy: types.string(),
  lastUpdatedDate: types.date(),
});

export function apiCredentialResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialResponseSchema' from JSON`,
  );
}
