/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ApiCredentialRolesSchema,
  ApiCredentialRolesSchema$Outbound,
  ApiCredentialRolesSchema$outboundSchema,
} from "./apicredentialrolesschema.js";

export type ApiCredentialUpdateRequestDTO = {
  /**
   * Human-readable name of the API Credential.
   */
  name?: string | undefined;
  /**
   * Brief description of the purpose and usage for the API Credential.
   */
  description?: string | undefined;
  /**
   * If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
   */
  enabled?: boolean | undefined;
  /**
   * Role assignments for the API Credential.
   */
  roles?: ApiCredentialRolesSchema | undefined;
  /**
   * Omit to leave unchanged. Pass an empty array to clear the stored IP allowlist.
   */
  ipAllowlist?: Array<string> | undefined;
};

/** @internal */
export type ApiCredentialUpdateRequestDTO$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  roles?: ApiCredentialRolesSchema$Outbound | undefined;
  ipAllowlist?: Array<string> | undefined;
};

/** @internal */
export const ApiCredentialUpdateRequestDTO$outboundSchema: z.ZodType<
  ApiCredentialUpdateRequestDTO$Outbound,
  z.ZodTypeDef,
  ApiCredentialUpdateRequestDTO
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  roles: ApiCredentialRolesSchema$outboundSchema.optional(),
  ipAllowlist: z.array(z.string()).optional(),
});

export function apiCredentialUpdateRequestDTOToJSON(
  apiCredentialUpdateRequestDTO: ApiCredentialUpdateRequestDTO,
): string {
  return JSON.stringify(
    ApiCredentialUpdateRequestDTO$outboundSchema.parse(
      apiCredentialUpdateRequestDTO,
    ),
  );
}
