/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WorkspaceRoleSchema,
  WorkspaceRoleSchema$inboundSchema,
  WorkspaceRoleSchema$Outbound,
  WorkspaceRoleSchema$outboundSchema,
} from "./workspaceroleschema.js";

/**
 * Organization-level Role assigned to the API Credential.
 */
export const OrganizationRole = {
  Owner: "owner",
  Admin: "admin",
  User: "user",
} as const;
/**
 * Organization-level Role assigned to the API Credential.
 */
export type OrganizationRole = OpenEnum<typeof OrganizationRole>;

export type ApiCredentialRolesSchema = {
  /**
   * Organization-level Role assigned to the API Credential.
   */
  organizationRole: OrganizationRole;
  /**
   * Workspace-level Roles assigned to the API Credential.
   */
  workspaces?: Array<WorkspaceRoleSchema> | undefined;
};

/** @internal */
export const OrganizationRole$inboundSchema: z.ZodType<
  OrganizationRole,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(OrganizationRole);
/** @internal */
export const OrganizationRole$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  OrganizationRole
> = openEnums.outboundSchema(OrganizationRole);

/** @internal */
export const ApiCredentialRolesSchema$inboundSchema: z.ZodType<
  ApiCredentialRolesSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationRole: OrganizationRole$inboundSchema,
  workspaces: types.optional(z.array(WorkspaceRoleSchema$inboundSchema)),
});
/** @internal */
export type ApiCredentialRolesSchema$Outbound = {
  organizationRole: string;
  workspaces?: Array<WorkspaceRoleSchema$Outbound> | undefined;
};

/** @internal */
export const ApiCredentialRolesSchema$outboundSchema: z.ZodType<
  ApiCredentialRolesSchema$Outbound,
  z.ZodTypeDef,
  ApiCredentialRolesSchema
> = z.object({
  organizationRole: OrganizationRole$outboundSchema,
  workspaces: z.array(WorkspaceRoleSchema$outboundSchema).optional(),
});

export function apiCredentialRolesSchemaToJSON(
  apiCredentialRolesSchema: ApiCredentialRolesSchema,
): string {
  return JSON.stringify(
    ApiCredentialRolesSchema$outboundSchema.parse(apiCredentialRolesSchema),
  );
}
export function apiCredentialRolesSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialRolesSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialRolesSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialRolesSchema' from JSON`,
  );
}
