/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiCredentialListItemSchema,
  ApiCredentialListItemSchema$inboundSchema,
} from "./apicredentiallistitemschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiCredentialsListResponseDTO = {
  /**
   * List of API Credentials.
   */
  items: Array<ApiCredentialListItemSchema>;
  /**
   * Total number of API Credentials listed in the response.
   */
  count: number;
};

/** @internal */
export const ApiCredentialsListResponseDTO$inboundSchema: z.ZodType<
  ApiCredentialsListResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(ApiCredentialListItemSchema$inboundSchema),
  count: types.number(),
});

export function apiCredentialsListResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialsListResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialsListResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialsListResponseDTO' from JSON`,
  );
}
