/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WorkspaceRoleSchema,
  WorkspaceRoleSchema$inboundSchema,
} from "./workspaceroleschema.js";

/**
 * Organization-level role
 */
export const OrganizationRole = {
  Owner: "owner",
  Admin: "admin",
  User: "user",
} as const;
/**
 * Organization-level role
 */
export type OrganizationRole = OpenEnum<typeof OrganizationRole>;

export type ApiCredentialRolesSchema = {
  /**
   * Organization-level role
   */
  organizationRole: OrganizationRole;
  /**
   * Workspace roles assigned to this credential
   */
  workspaces?: Array<WorkspaceRoleSchema> | undefined;
};

/** @internal */
export const OrganizationRole$inboundSchema: z.ZodType<
  OrganizationRole,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(OrganizationRole);

/** @internal */
export const ApiCredentialRolesSchema$inboundSchema: z.ZodType<
  ApiCredentialRolesSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationRole: OrganizationRole$inboundSchema,
  workspaces: types.optional(z.array(WorkspaceRoleSchema$inboundSchema)),
});

export function apiCredentialRolesSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ApiCredentialRolesSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCredentialRolesSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCredentialRolesSchema' from JSON`,
  );
}
