/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const BillingWindow = {
  Monthly: "monthly",
  Daily: "daily",
} as const;
export type BillingWindow = OpenEnum<typeof BillingWindow>;

/** @internal */
export const BillingWindow$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  BillingWindow
> = openEnums.outboundSchema(BillingWindow);
