/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ContractUtilizationSchema,
  ContractUtilizationSchema$inboundSchema,
} from "./contractutilizationschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ContractsUtilizationResponseDTO = {
  /**
   * Contract utilization data, grouped by contract period.
   */
  contracts: Array<ContractUtilizationSchema>;
};

/** @internal */
export const ContractsUtilizationResponseDTO$inboundSchema: z.ZodType<
  ContractsUtilizationResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  contracts: z.array(ContractUtilizationSchema$inboundSchema),
});

export function contractsUtilizationResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<ContractsUtilizationResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContractsUtilizationResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContractsUtilizationResponseDTO' from JSON`,
  );
}
