/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditsUtilizationItemSchema,
  CreditsUtilizationItemSchema$inboundSchema,
} from "./creditsutilizationitemschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ContractUtilizationSchema = {
  /**
   * Contract start date in ISO 8601 format.
   */
  contractStartDate: Date;
  /**
   * Contract end date in ISO 8601 format. Present only when the contract is closed.
   */
  contractEndDate?: Date | undefined;
  /**
   * Cumulative credit utilization entries for the contract.
   */
  items: Array<CreditsUtilizationItemSchema>;
};

/** @internal */
export const ContractUtilizationSchema$inboundSchema: z.ZodType<
  ContractUtilizationSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  contractStartDate: types.date(),
  contractEndDate: types.optional(types.date()),
  items: z.array(CreditsUtilizationItemSchema$inboundSchema),
});

export function contractUtilizationSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ContractUtilizationSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContractUtilizationSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContractUtilizationSchema' from JSON`,
  );
}
