/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditsTimeseriesItemSchema,
  CreditsTimeseriesItemSchema$inboundSchema,
} from "./creditstimeseriesitemschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsTimeseriesResponseDTO = {
  /**
   * Credit timeseries data points.
   */
  items: Array<CreditsTimeseriesItemSchema>;
  /**
   * Total number of items in the response.
   */
  count: number;
};

/** @internal */
export const CreditsTimeseriesResponseDTO$inboundSchema: z.ZodType<
  CreditsTimeseriesResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(CreditsTimeseriesItemSchema$inboundSchema),
  count: types.number(),
});

export function creditsTimeseriesResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<CreditsTimeseriesResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsTimeseriesResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsTimeseriesResponseDTO' from JSON`,
  );
}
