/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditsTimeseriesDimensionSchema,
  CreditsTimeseriesDimensionSchema$inboundSchema,
} from "./creditstimeseriesdimensionschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsTimeseriesItemSchema = {
  /**
   * Date of the aggregation window in ISO 8601 format.
   */
  date: Date;
  /**
   * Total credits consumed in the aggregation window.
   */
  credits: number;
  /**
   * Credit breakdown by dimension.
   */
  dimensions: Array<CreditsTimeseriesDimensionSchema>;
};

/** @internal */
export const CreditsTimeseriesItemSchema$inboundSchema: z.ZodType<
  CreditsTimeseriesItemSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: types.date(),
  credits: types.number(),
  dimensions: z.array(CreditsTimeseriesDimensionSchema$inboundSchema),
});

export function creditsTimeseriesItemSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CreditsTimeseriesItemSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsTimeseriesItemSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsTimeseriesItemSchema' from JSON`,
  );
}
