/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditGrantSchema,
  CreditGrantSchema$inboundSchema,
} from "./creditgrantschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditGrantsResponseDTO = {
  /**
   * Credit grants for the queried period.
   */
  items: Array<CreditGrantSchema>;
  /**
   * Total number of items in the response.
   */
  count: number;
};

/** @internal */
export const CreditGrantsResponseDTO$inboundSchema: z.ZodType<
  CreditGrantsResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(CreditGrantSchema$inboundSchema),
  count: types.number(),
});

export function creditGrantsResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<CreditGrantsResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditGrantsResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditGrantsResponseDTO' from JSON`,
  );
}
