/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsUtilizationItemSchema = {
  /**
   * Date of the aggregation window in ISO 8601 format.
   */
  date: Date;
  /**
   * Number of credits consumed in the aggregation window.
   */
  credits: number;
};

/** @internal */
export const CreditsUtilizationItemSchema$inboundSchema: z.ZodType<
  CreditsUtilizationItemSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: types.date(),
  credits: types.number(),
});

export function creditsUtilizationItemSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CreditsUtilizationItemSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsUtilizationItemSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsUtilizationItemSchema' from JSON`,
  );
}
