/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditsStatsContractSchema,
  CreditsStatsContractSchema$inboundSchema,
} from "./creditsstatscontractschema.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsStatsResponseDTO = {
  /**
   * Total credits remaining across all contracts.
   */
  totalCreditsRemaining: number;
  /**
   * Total credits consumed across all contracts.
   */
  totalCreditsUsed: number;
  /**
   * Total credits acquired across all contracts.
   */
  totalCreditsAcquired: number;
  /**
   * Contract periods ordered by contract start date in reverse chronological order (newest first).
   */
  contracts?: Array<CreditsStatsContractSchema> | undefined;
};

/** @internal */
export const CreditsStatsResponseDTO$inboundSchema: z.ZodType<
  CreditsStatsResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalCreditsRemaining: types.number(),
  totalCreditsUsed: types.number(),
  totalCreditsAcquired: types.number(),
  contracts: types.optional(z.array(CreditsStatsContractSchema$inboundSchema)),
});

export function creditsStatsResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<CreditsStatsResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsStatsResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsStatsResponseDTO' from JSON`,
  );
}
