/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsStatsContractSchema = {
  /**
   * Contract start date in ISO 8601 format.
   */
  startDate: Date;
  /**
   * Contract end date in ISO 8601 format. Present only when the contract is closed.
   */
  endDate?: Date | undefined;
};

/** @internal */
export const CreditsStatsContractSchema$inboundSchema: z.ZodType<
  CreditsStatsContractSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  startDate: types.date(),
  endDate: types.optional(types.date()),
});

export function creditsStatsContractSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CreditsStatsContractSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsStatsContractSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsStatsContractSchema' from JSON`,
  );
}
