/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreditsTimeseriesDimensionSchema = {
  /**
   * Dimension label for the credit breakdown.
   */
  dimension: string;
  /**
   * Number of credits attributed to the dimension.
   */
  credits: number;
};

/** @internal */
export const CreditsTimeseriesDimensionSchema$inboundSchema: z.ZodType<
  CreditsTimeseriesDimensionSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  dimension: types.string(),
  credits: types.number(),
});

export function creditsTimeseriesDimensionSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CreditsTimeseriesDimensionSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditsTimeseriesDimensionSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditsTimeseriesDimensionSchema' from JSON`,
  );
}
