/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Type of the credit grant.
 */
export const Type = {
  Refund: "Refund",
  Rollover: "Rollover",
  Purchased: "Purchased",
} as const;
/**
 * Type of the credit grant.
 */
export type Type = OpenEnum<typeof Type>;

export type CreditGrantSchema = {
  /**
   * Date the grant was issued, in ISO 8601 format.
   */
  date: Date;
  /**
   * Number of credits acquired by the grant.
   */
  creditsAcquired: number;
  /**
   * Type of the credit grant.
   */
  type: Type;
};

/** @internal */
export const Type$inboundSchema: z.ZodType<Type, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Type);

/** @internal */
export const CreditGrantSchema$inboundSchema: z.ZodType<
  CreditGrantSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: types.date(),
  creditsAcquired: types.number(),
  type: Type$inboundSchema,
});

export function creditGrantSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CreditGrantSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditGrantSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditGrantSchema' from JSON`,
  );
}
