/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DefaultErrorDTO = {
  statusCode: number;
  message: string;
};

/** @internal */
export const DefaultErrorDTO$inboundSchema: z.ZodType<
  DefaultErrorDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  statusCode: z.number(),
  message: z.string(),
});

export function defaultErrorDTOFromJSON(
  jsonString: string,
): SafeParseResult<DefaultErrorDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefaultErrorDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefaultErrorDTO' from JSON`,
  );
}
