/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Product name.
 */
export const Product = {
  Edge: "edge",
  Search: "search",
  Stream: "stream",
  Lake: "lake",
} as const;
/**
 * Product name.
 */
export type Product = OpenEnum<typeof Product>;

/**
 * Role assigned to the API Credential on the product.
 */
export const Role = {
  Admin: "admin",
  Editor: "editor",
  Reader: "reader",
  User: "user",
  Noaccess: "noaccess",
} as const;
/**
 * Role assigned to the API Credential on the product.
 */
export type Role = OpenEnum<typeof Role>;

export type ProductRoleSchema = {
  /**
   * Product name.
   */
  product: Product;
  /**
   * Role assigned to the API Credential on the product.
   */
  role: Role;
};

/** @internal */
export const Product$inboundSchema: z.ZodType<Product, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Product);
/** @internal */
export const Product$outboundSchema: z.ZodType<string, z.ZodTypeDef, Product> =
  openEnums.outboundSchema(Product);

/** @internal */
export const Role$inboundSchema: z.ZodType<Role, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Role);
/** @internal */
export const Role$outboundSchema: z.ZodType<string, z.ZodTypeDef, Role> =
  openEnums.outboundSchema(Role);

/** @internal */
export const ProductRoleSchema$inboundSchema: z.ZodType<
  ProductRoleSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  product: Product$inboundSchema,
  role: Role$inboundSchema,
});
/** @internal */
export type ProductRoleSchema$Outbound = {
  product: string;
  role: string;
};

/** @internal */
export const ProductRoleSchema$outboundSchema: z.ZodType<
  ProductRoleSchema$Outbound,
  z.ZodTypeDef,
  ProductRoleSchema
> = z.object({
  product: Product$outboundSchema,
  role: Role$outboundSchema,
});

export function productRoleSchemaToJSON(
  productRoleSchema: ProductRoleSchema,
): string {
  return JSON.stringify(
    ProductRoleSchema$outboundSchema.parse(productRoleSchema),
  );
}
export function productRoleSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ProductRoleSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductRoleSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductRoleSchema' from JSON`,
  );
}
