/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SchemeOauth2 = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export const SchemeOauth2$inboundSchema: z.ZodType<
  SchemeOauth2,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://login.cribl.cloud/oauth2/token"),
});

/** @internal */
export type SchemeOauth2$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const SchemeOauth2$outboundSchema: z.ZodType<
  SchemeOauth2$Outbound,
  z.ZodTypeDef,
  SchemeOauth2
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://login.cribl.cloud/oauth2/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SchemeOauth2$ {
  /** @deprecated use `SchemeOauth2$inboundSchema` instead. */
  export const inboundSchema = SchemeOauth2$inboundSchema;
  /** @deprecated use `SchemeOauth2$outboundSchema` instead. */
  export const outboundSchema = SchemeOauth2$outboundSchema;
  /** @deprecated use `SchemeOauth2$Outbound` instead. */
  export type Outbound = SchemeOauth2$Outbound;
}

export function schemeOauth2ToJSON(schemeOauth2: SchemeOauth2): string {
  return JSON.stringify(SchemeOauth2$outboundSchema.parse(schemeOauth2));
}

export function schemeOauth2FromJSON(
  jsonString: string,
): SafeParseResult<SchemeOauth2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemeOauth2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemeOauth2' from JSON`,
  );
}
