/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  SchemeClientOauth,
  SchemeClientOauth$Outbound,
  SchemeClientOauth$outboundSchema,
} from "./schemeclientoauth.js";

export type Security = {
  clientOauth?: SchemeClientOauth | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  clientOauth?: SchemeClientOauth$Outbound | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  clientOauth: SchemeClientOauth$outboundSchema.optional(),
  bearerAuth: z.string().optional(),
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
