/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WorkspaceSchema,
  WorkspaceSchema$inboundSchema,
} from "./workspaceschema.js";

export type WorkspacesListResponseDTO = {
  /**
   * List of workspaces
   */
  items: Array<WorkspaceSchema>;
  /**
   * Total number of workspaces
   */
  count: number;
};

/** @internal */
export const WorkspacesListResponseDTO$inboundSchema: z.ZodType<
  WorkspacesListResponseDTO,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(WorkspaceSchema$inboundSchema),
  count: types.number(),
});

export function workspacesListResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<WorkspacesListResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspacesListResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspacesListResponseDTO' from JSON`,
  );
}
