/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * AWS region where the Workspace is deployed.
 */
export const Region = {
  UsWest2: "us-west-2",
  UsEast1: "us-east-1",
  UsEast2: "us-east-2",
  EuCentral1: "eu-central-1",
  EuCentral2: "eu-central-2",
  EuWest2: "eu-west-2",
  ApSoutheast1: "ap-southeast-1",
  ApSoutheast2: "ap-southeast-2",
  CaCentral1: "ca-central-1",
  ApNortheast1: "ap-northeast-1",
  SaEast1: "sa-east-1",
  EuWest1: "eu-west-1",
  EuWest3: "eu-west-3",
} as const;
/**
 * AWS region where the Workspace is deployed.
 */
export type Region = OpenEnum<typeof Region>;

/**
 * Current state of the Workspace.
 */
export const State = {
  Provisioning: "Provisioning",
  Active: "Active",
  Inactive: "Inactive",
  Failed: "Failed",
  Deprovisioning: "Deprovisioning",
} as const;
/**
 * Current state of the Workspace.
 */
export type State = OpenEnum<typeof State>;

export type WorkspaceSchema = {
  /**
   * Unique identifier for the Workspace.
   */
  workspaceId: string;
  /**
   * AWS region where the Workspace is deployed.
   */
  region: Region;
  /**
   * Fully Qualified Domain Name (FQDN) of the Workspace Leader.
   */
  leaderFQDN: string;
  /**
   * Current state of the Workspace.
   */
  state: State;
  /**
   * User-friendly alias for the Workspace.
   */
  alias?: string | undefined;
  /**
   * Brief description of the Workspace.
   */
  description?: string | undefined;
  /**
   * Tags associated with the Workspace.
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export const Region$inboundSchema: z.ZodType<Region, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Region);

/** @internal */
export const State$inboundSchema: z.ZodType<State, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(State);

/** @internal */
export const WorkspaceSchema$inboundSchema: z.ZodType<
  WorkspaceSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: types.string(),
  region: Region$inboundSchema,
  leaderFQDN: types.string(),
  state: State$inboundSchema,
  alias: types.optional(types.string()),
  description: types.optional(types.string()),
  tags: types.optional(z.array(types.string())),
});

export function workspaceSchemaFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceSchema' from JSON`,
  );
}
