/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type WorkspacePatchRequestDTO = {
  /**
   * User-friendly alias for the Workspace.
   */
  alias?: string | undefined;
  /**
   * Brief description of the Workspace.
   */
  description?: string | undefined;
  /**
   * Tags associated with the Workspace.
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export type WorkspacePatchRequestDTO$Outbound = {
  alias?: string | undefined;
  description?: string | undefined;
  tags?: Array<string> | undefined;
};

/** @internal */
export const WorkspacePatchRequestDTO$outboundSchema: z.ZodType<
  WorkspacePatchRequestDTO$Outbound,
  z.ZodTypeDef,
  WorkspacePatchRequestDTO
> = z.object({
  alias: z.string().optional(),
  description: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

export function workspacePatchRequestDTOToJSON(
  workspacePatchRequestDTO: WorkspacePatchRequestDTO,
): string {
  return JSON.stringify(
    WorkspacePatchRequestDTO$outboundSchema.parse(workspacePatchRequestDTO),
  );
}
