/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type WorkspaceCreateRequestDTO = {
  /**
   * Unique identifier for the Workspace.
   */
  workspaceId: string;
  /**
   * User-friendly alias for the Workspace.
   */
  alias?: string | undefined;
  /**
   * Brief description of the Workspace.
   */
  description?: string | undefined;
  /**
   * Tags associated with the Workspace.
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export type WorkspaceCreateRequestDTO$Outbound = {
  workspaceId: string;
  alias?: string | undefined;
  description?: string | undefined;
  tags?: Array<string> | undefined;
};

/** @internal */
export const WorkspaceCreateRequestDTO$outboundSchema: z.ZodType<
  WorkspaceCreateRequestDTO$Outbound,
  z.ZodTypeDef,
  WorkspaceCreateRequestDTO
> = z.object({
  workspaceId: z.string(),
  alias: z.string().optional(),
  description: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

export function workspaceCreateRequestDTOToJSON(
  workspaceCreateRequestDTO: WorkspaceCreateRequestDTO,
): string {
  return JSON.stringify(
    WorkspaceCreateRequestDTO$outboundSchema.parse(workspaceCreateRequestDTO),
  );
}
