/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProductRoleSchema,
  ProductRoleSchema$inboundSchema,
} from "./productroleschema.js";

/**
 * Role in the workspace
 */
export const WorkspaceRole = {
  Owner: "owner",
  Admin: "admin",
  User: "user",
  Noaccess: "noaccess",
} as const;
/**
 * Role in the workspace
 */
export type WorkspaceRole = OpenEnum<typeof WorkspaceRole>;

export type WorkspaceRoleSchema = {
  /**
   * Workspace identifier
   */
  workspaceId: string;
  /**
   * Role in the workspace
   */
  workspaceRole: WorkspaceRole;
  /**
   * Product roles in the workspace
   */
  products?: Array<ProductRoleSchema> | undefined;
};

/** @internal */
export const WorkspaceRole$inboundSchema: z.ZodType<
  WorkspaceRole,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(WorkspaceRole);

/** @internal */
export const WorkspaceRoleSchema$inboundSchema: z.ZodType<
  WorkspaceRoleSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: types.string(),
  workspaceRole: WorkspaceRole$inboundSchema,
  products: types.optional(z.array(ProductRoleSchema$inboundSchema)),
});

export function workspaceRoleSchemaFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceRoleSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceRoleSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceRoleSchema' from JSON`,
  );
}
