/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProductRoleSchema,
  ProductRoleSchema$inboundSchema,
  ProductRoleSchema$Outbound,
  ProductRoleSchema$outboundSchema,
} from "./productroleschema.js";

/**
 * Role assigned to the API Credential on the Workspace.
 */
export const WorkspaceRole = {
  Owner: "owner",
  Admin: "admin",
  User: "user",
  Noaccess: "noaccess",
} as const;
/**
 * Role assigned to the API Credential on the Workspace.
 */
export type WorkspaceRole = OpenEnum<typeof WorkspaceRole>;

export type WorkspaceRoleSchema = {
  /**
   * Unique ID of the Workspace.
   */
  workspaceId: string;
  /**
   * Role assigned to the API Credential on the Workspace.
   */
  workspaceRole: WorkspaceRole;
  /**
   * Product-level Roles assigned to the API Credential for the Workspace.
   */
  products?: Array<ProductRoleSchema> | undefined;
};

/** @internal */
export const WorkspaceRole$inboundSchema: z.ZodType<
  WorkspaceRole,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(WorkspaceRole);
/** @internal */
export const WorkspaceRole$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  WorkspaceRole
> = openEnums.outboundSchema(WorkspaceRole);

/** @internal */
export const WorkspaceRoleSchema$inboundSchema: z.ZodType<
  WorkspaceRoleSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: types.string(),
  workspaceRole: WorkspaceRole$inboundSchema,
  products: types.optional(z.array(ProductRoleSchema$inboundSchema)),
});
/** @internal */
export type WorkspaceRoleSchema$Outbound = {
  workspaceId: string;
  workspaceRole: string;
  products?: Array<ProductRoleSchema$Outbound> | undefined;
};

/** @internal */
export const WorkspaceRoleSchema$outboundSchema: z.ZodType<
  WorkspaceRoleSchema$Outbound,
  z.ZodTypeDef,
  WorkspaceRoleSchema
> = z.object({
  workspaceId: z.string(),
  workspaceRole: WorkspaceRole$outboundSchema,
  products: z.array(ProductRoleSchema$outboundSchema).optional(),
});

export function workspaceRoleSchemaToJSON(
  workspaceRoleSchema: WorkspaceRoleSchema,
): string {
  return JSON.stringify(
    WorkspaceRoleSchema$outboundSchema.parse(workspaceRoleSchema),
  );
}
export function workspaceRoleSchemaFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceRoleSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceRoleSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceRoleSchema' from JSON`,
  );
}
